CREATE TABLE IF NOT EXISTS users (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    birthday DATE
    );

CREATE TABLE IF NOT EXISTS mpa (
                                   id INTEGER PRIMARY KEY,
                                   name VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS genres (
                                      id INTEGER PRIMARY KEY,
                                      name VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS films (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER NOT NULL,
    mpa_id INTEGER,

    CONSTRAINT fk_films_mpa
    FOREIGN KEY (mpa_id)
    REFERENCES mpa(id)
    );

CREATE TABLE IF NOT EXISTS film_genres (
                                           film_id INTEGER NOT NULL,
                                           genre_id INTEGER NOT NULL,

                                           PRIMARY KEY (film_id, genre_id),

    CONSTRAINT fk_film_genres_film
    FOREIGN KEY (film_id)
    REFERENCES films(id)
    ON DELETE CASCADE,

    CONSTRAINT fk_film_genres_genre
    FOREIGN KEY (genre_id)
    REFERENCES genres(id)
    );

CREATE TABLE IF NOT EXISTS likes (
                                     film_id INTEGER NOT NULL,
                                     user_id INTEGER NOT NULL,

                                     PRIMARY KEY (film_id, user_id),

    CONSTRAINT fk_likes_film
    FOREIGN KEY (film_id)
    REFERENCES films(id)
    ON DELETE CASCADE,

    CONSTRAINT fk_likes_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS friendships (
                                           user_id INTEGER NOT NULL,
                                           friend_id INTEGER NOT NULL,

                                           PRIMARY KEY (user_id, friend_id),

    CONSTRAINT fk_friendships_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE,

    CONSTRAINT fk_friendships_friend
    FOREIGN KEY (friend_id)
    REFERENCES users(id)
    ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_film_genres_film_id
    ON film_genres(film_id);

CREATE INDEX IF NOT EXISTS idx_likes_film_id
    ON likes(film_id);

CREATE INDEX IF NOT EXISTS idx_friendships_user_id
    ON friendships(user_id);